### ISSUE TITLE
order the options in a row from safe to dangerous

### ISSUE THREAD

**Issue by helmiYG** [fajartc02/be_coolant_mgmt_sys#3]
in the current api for getting parameter checking in the Sludge prameter, the first option status is danger, but in Visual parameter, the option status is ordered from safe to dangerous (inconsistent). please order it from safest to dangerous for consistency.

**Comment by fajartc02** [comment]
sudah close ya pak..
di assign dong ke siapanya sama di kasih label wkwkwk
